export const dummyUsers = [
  {
    id: '1',
    name: 'Rajesh Kumar',
    email: 'rajesh.kumar@email.com',
    phone: '+91-9876543210',
    verified: true,
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=1',
    createdAt: new Date('2024-01-15'),
  },
  {
    id: '2',
    name: 'Priya Singh',
    email: 'priya.singh@email.com',
    phone: '+91-9876543211',
    verified: true,
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=2',
    createdAt: new Date('2024-02-20'),
  },
  {
    id: '3',
    name: 'Amit Patel',
    email: 'amit.patel@email.com',
    phone: '+91-9876543212',
    verified: false,
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=3',
    createdAt: new Date('2024-03-10'),
  },
  {
    id: '4',
    name: 'Neha Sharma',
    email: 'neha.sharma@email.com',
    phone: '+91-9876543213',
    verified: true,
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=4',
    createdAt: new Date('2024-01-25'),
  },
  {
    id: '5',
    name: 'Vikram Singh',
    email: 'vikram.singh@email.com',
    phone: '+91-9876543214',
    verified: false,
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=5',
    createdAt: new Date('2024-03-05'),
  },
  {
    id: '6',
    name: 'Anjali Verma',
    email: 'anjali.verma@email.com',
    phone: '+91-9876543215',
    verified: true,
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=6',
    createdAt: new Date('2024-02-14'),
  },
  {
    id: '7',
    name: 'Sanjay Gupta',
    email: 'sanjay.gupta@email.com',
    phone: '+91-9876543216',
    verified: true,
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=7',
    createdAt: new Date('2024-01-30'),
  },
  {
    id: '8',
    name: 'Meera Nair',
    email: 'meera.nair@email.com',
    phone: '+91-9876543217',
    verified: false,
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=8',
    createdAt: new Date('2024-03-18'),
  },
];

export const dummyAgents = [
  {
    id: '1',
    name: 'Wanderlust Travels',
    email: 'contact@wanderlust.com',
    phone: '+91-8765432100',
    approvalStatus: 'approved',
    profileImage: 'https://api.dicebear.com/7.x/initials/svg?seed=WT',
    rating: 4.8,
    packages: 12,
    totalBookings: 156,
  },
  {
    id: '2',
    name: 'Journey Express',
    email: 'info@journeyexpress.com',
    phone: '+91-8765432101',
    approvalStatus: 'pending',
    profileImage: 'https://api.dicebear.com/7.x/initials/svg?seed=JE',
    rating: 4.5,
    packages: 8,
    totalBookings: 89,
  },
  {
    id: '3',
    name: 'Global Getaways',
    email: 'support@globalgetaways.com',
    phone: '+91-8765432102',
    approvalStatus: 'approved',
    profileImage: 'https://api.dicebear.com/7.x/initials/svg?seed=GG',
    rating: 4.9,
    packages: 18,
    totalBookings: 234,
  },
  {
    id: '4',
    name: 'Adventure Seekers',
    email: 'hello@adventureseekers.com',
    phone: '+91-8765432103',
    approvalStatus: 'rejected',
    profileImage: 'https://api.dicebear.com/7.x/initials/svg?seed=AS',
    rating: 4.3,
    packages: 5,
    totalBookings: 42,
  },
  {
    id: '5',
    name: 'Exotic Escapes',
    email: 'bookings@exoticescapes.com',
    phone: '+91-8765432104',
    approvalStatus: 'approved',
    profileImage: 'https://api.dicebear.com/7.x/initials/svg?seed=EE',
    rating: 4.7,
    packages: 14,
    totalBookings: 178,
  },
];

export const dummyPackages = [
  {
    id: '1',
    name: 'Bali Paradise',
    destination: 'Bali, Indonesia',
    image: 'https://images.unsplash.com/photo-1537225228614-56cc3556d7ed?w=400&h=300&fit=crop',
    approvalStatus: 'approved',
    agentId: '1',
    agentName: 'Wanderlust Travels',
    price: 45000,
    duration: 5,
    basePrice: 35000,
    rating: 4.6,
    bookings: 23,
  },
  {
    id: '2',
    name: 'Swiss Alps Adventure',
    destination: 'Switzerland',
    image: 'https://images.unsplash.com/photo-1531366936337-7793a028169d?w=400&h=300&fit=crop',
    approvalStatus: 'approved',
    agentId: '1',
    agentName: 'Wanderlust Travels',
    price: 125000,
    duration: 10,
    basePrice: 95000,
    rating: 4.9,
    bookings: 34,
  },
  {
    id: '3',
    name: 'Kerala Backwaters',
    destination: 'Kerala, India',
    image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=400&h=300&fit=crop',
    approvalStatus: 'pending',
    agentId: '3',
    agentName: 'Global Getaways',
    price: 32000,
    duration: 4,
    basePrice: 25000,
    rating: 4.5,
    bookings: 15,
  },
  {
    id: '4',
    name: 'Tokyo City Tour',
    destination: 'Japan',
    image: 'https://images.unsplash.com/photo-1540959375944-7049f642e9bf?w=400&h=300&fit=crop',
    approvalStatus: 'approved',
    agentId: '3',
    agentName: 'Global Getaways',
    price: 75000,
    duration: 6,
    basePrice: 55000,
    rating: 4.7,
    bookings: 28,
  },
  {
    id: '5',
    name: 'Greece Island Hopping',
    destination: 'Greece',
    image: 'https://images.unsplash.com/photo-1570059405234-6e80aca4bb5a?w=400&h=300&fit=crop',
    approvalStatus: 'approved',
    agentId: '5',
    agentName: 'Exotic Escapes',
    price: 95000,
    duration: 8,
    basePrice: 72000,
    rating: 4.8,
    bookings: 31,
  },
  {
    id: '6',
    name: 'Goa Beach Escape',
    destination: 'Goa, India',
    image: 'https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?w=400&h=300&fit=crop',
    approvalStatus: 'rejected',
    agentId: '2',
    agentName: 'Journey Express',
    price: 28000,
    duration: 3,
    basePrice: 20000,
    rating: 4.2,
    bookings: 8,
  },
  {
    id: '7',
    name: 'Rajasthan Royal',
    destination: 'Rajasthan, India',
    image: 'https://images.unsplash.com/photo-1548013146-72d72b7730ce?w=400&h=300&fit=crop',
    approvalStatus: 'approved',
    agentId: '5',
    agentName: 'Exotic Escapes',
    price: 55000,
    duration: 7,
    basePrice: 40000,
    rating: 4.6,
    bookings: 19,
  },
];

export const dummyBookings = [
  {
    id: '1',
    userId: '1',
    userName: 'Rajesh Kumar',
    packageId: '1',
    packageName: 'Bali Paradise',
    agentName: 'Wanderlust Travels',
    bookingDate: new Date('2024-03-01'),
    startDate: new Date('2024-04-10'),
    endDate: new Date('2024-04-15'),
    totalPrice: 135000,
    numberOfPeople: 3,
    status: 'confirmed',
  },
  {
    id: '2',
    userId: '2',
    userName: 'Priya Singh',
    packageId: '2',
    packageName: 'Swiss Alps Adventure',
    agentName: 'Wanderlust Travels',
    bookingDate: new Date('2024-02-28'),
    startDate: new Date('2024-05-20'),
    endDate: new Date('2024-05-30'),
    totalPrice: 375000,
    numberOfPeople: 2,
    status: 'confirmed',
  },
  {
    id: '3',
    userId: '4',
    userName: 'Neha Sharma',
    packageId: '3',
    packageName: 'Kerala Backwaters',
    agentName: 'Global Getaways',
    bookingDate: new Date('2024-03-05'),
    startDate: new Date('2024-04-20'),
    endDate: new Date('2024-04-24'),
    totalPrice: 96000,
    numberOfPeople: 3,
    status: 'confirmed',
  },
  {
    id: '4',
    userId: '6',
    userName: 'Anjali Verma',
    packageId: '4',
    packageName: 'Tokyo City Tour',
    agentName: 'Global Getaways',
    bookingDate: new Date('2024-03-08'),
    startDate: new Date('2024-06-10'),
    endDate: new Date('2024-06-16'),
    totalPrice: 150000,
    numberOfPeople: 2,
    status: 'pending',
  },
  {
    id: '5',
    userId: '7',
    userName: 'Sanjay Gupta',
    packageId: '5',
    packageName: 'Greece Island Hopping',
    agentName: 'Exotic Escapes',
    bookingDate: new Date('2024-03-02'),
    startDate: new Date('2024-07-01'),
    endDate: new Date('2024-07-09'),
    totalPrice: 285000,
    numberOfPeople: 2,
    status: 'confirmed',
  },
  {
    id: '6',
    userId: '3',
    userName: 'Amit Patel',
    packageId: '7',
    packageName: 'Rajasthan Royal',
    agentName: 'Exotic Escapes',
    bookingDate: new Date('2024-03-10'),
    startDate: new Date('2024-05-15'),
    endDate: new Date('2024-05-22'),
    totalPrice: 110000,
    numberOfPeople: 2,
    status: 'cancelled',
  },
];

export const dummyPayments = [
  {
    id: '1',
    bookingId: '1',
    amount: 135000,
    type: 'booking',
    status: 'success',
    paymentDate: new Date('2024-03-01'),
    method: 'card',
    transactionId: 'TXN001234567',
  },
  {
    id: '2',
    bookingId: '2',
    amount: 375000,
    type: 'booking',
    status: 'success',
    paymentDate: new Date('2024-02-28'),
    method: 'upi',
    transactionId: 'TXN001234568',
  },
  {
    id: '3',
    bookingId: '3',
    amount: 96000,
    type: 'booking',
    status: 'success',
    paymentDate: new Date('2024-03-05'),
    method: 'card',
    transactionId: 'TXN001234569',
  },
  {
    id: '4',
    bookingId: '6',
    amount: 55000,
    type: 'refund',
    status: 'success',
    paymentDate: new Date('2024-03-12'),
    method: 'card',
    transactionId: 'TXN001234570',
  },
  {
    id: '5',
    bookingId: '4',
    amount: 150000,
    type: 'booking',
    status: 'pending',
    paymentDate: new Date('2024-03-08'),
    method: 'card',
    transactionId: 'TXN001234571',
  },
  {
    id: '6',
    bookingId: '5',
    amount: 285000,
    type: 'booking',
    status: 'success',
    paymentDate: new Date('2024-03-02'),
    method: 'upi',
    transactionId: 'TXN001234572',
  },
  {
    id: '7',
    bookingId: '1',
    amount: 20000,
    type: 'refund',
    status: 'failed',
    paymentDate: new Date('2024-03-15'),
    method: 'card',
    transactionId: 'TXN001234573',
  },
];

export const dummySubAdmins = [
  {
    id: '1',
    name: 'Ravi Kumar',
    email: 'ravi.admin@batoibhai.com',
    phone: '+91-9876543220',
    approvalStatus: 'approved',
    address: '123 Admin Street, Mumbai, India',
    city: 'Mumbai',
    state: 'Maharashtra',
    pincode: '400001',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=ravi',
    createdAt: new Date('2024-01-10'),
  },
  {
    id: '2',
    name: 'Divya Patel',
    email: 'divya.admin@batoibhai.com',
    phone: '+91-9876543221',
    approvalStatus: 'approved',
    address: '456 Management Road, Bangalore, India',
    city: 'Bangalore',
    state: 'Karnataka',
    pincode: '560001',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=divya',
    createdAt: new Date('2024-02-05'),
  },
  {
    id: '3',
    name: 'Arun Singh',
    email: 'arun.admin@batoibhai.com',
    phone: '+91-9876543222',
    approvalStatus: 'pending',
    address: '789 Operations Lane, Delhi, India',
    city: 'Delhi',
    state: 'Delhi',
    pincode: '110001',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=arun',
    createdAt: new Date('2024-03-01'),
  },
  {
    id: '4',
    name: 'Neha Gupta',
    email: 'neha.admin@batoibhai.com',
    phone: '+91-9876543223',
    approvalStatus: 'rejected',
    address: '321 Support Avenue, Pune, India',
    city: 'Pune',
    state: 'Maharashtra',
    pincode: '411001',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=neha',
    createdAt: new Date('2024-02-20'),
  },
];

export const dummyStatistics = {
  totalRevenue: 1621000,
  totalBookings: 6,
  totalUsers: 8,
  totalAgents: 5,
  totalPackages: 7,
  revenueByMonth: [
    { month: 'January', revenue: 245000 },
    { month: 'February', revenue: 415000 },
    { month: 'March', revenue: 961000 },
  ],
  paymentStatus: [
    { status: 'Success', count: 5, amount: 1501000 },
    { status: 'Pending', count: 1, amount: 150000 },
    { status: 'Failed', count: 1, amount: 20000 },
  ],
};
